import { EventItem } from './types';

export const categories = [
  'All',
  'Concert',
  'Club',
  'Festival',
  'Party',
  'Virtual',
  'Conference',
  'Movie',
  'Tech',
  'Dinner',
  'Other'
];

export const events: EventItem[] = [
  {
    id: '1',
    title: 'Synthwave Night: Neon Beats',
    description: 'A retro-futuristic music night featuring synth artists and immersive visuals.',
    date: '2026-02-12',
    time: '19:00',
    location: 'The Warehouse, Lagos',
    category: 'Music',
    image: '/images/event-synth.webp',
    tags: ['music', 'nightlife'],
    tickets: [
      {
        id: 't1-1',
        name: 'General Admission',
        price: 2000,
        currency: 'NGN',
        start_selling_date: '2026-01-01',
        end_selling_date: '2026-02-12',
        description: 'Access to the main floor and bar area.',
        quantity: 250,
      },
      {
        id: 't1-2',
        name: 'VIP',
        price: 5000,
        currency: 'NGN',
        start_selling_date: '2026-01-01',
        end_selling_date: '2026-02-12',
        description: 'Includes VIP seating and complimentary drink.',
        quantity: 50,
      },
    ],
  },
  {
    id: '2',
    title: 'Design Systems Workshop',
    description: 'Hands-on workshop on building scalable design systems for teams.',
    date: '2026-03-05',
    time: '09:30',
    location: 'Tech Hub, Abuja',
    category: 'Tech',
    image: '/images/event-design.webp',
    tags: ['design', 'workshop'],
    tickets: [
      {
        id: 't2-1',
        name: 'Early Bird',
        price: 15000,
        currency: 'NGN',
        start_selling_date: '2026-01-05',
        end_selling_date: '2026-02-10',
        description: 'Discounted ticket for early registrants.',
        quantity: 40,
      },
      {
        id: 't2-2',
        name: 'Standard',
        price: 20000,
        currency: 'NGN',
        start_selling_date: '2026-02-11',
        end_selling_date: '2026-03-05',
        quantity: 100,
      },
      {
        id: 't2-3',
        name: 'Student (Free)',
        price: 0,
        currency: 'NGN',
        start_selling_date: '2026-01-05',
        end_selling_date: '2026-03-05',
        description: 'Free ticket for students with valid ID.',
        quantity: 30,
      },
    ],
  },
  {
    id: '3',
    title: 'Open Mic & Poetry',
    description: 'An intimate evening of storytelling, poetry, and acoustic performances.',
    date: '2026-02-20',
    time: '18:00',
    location: 'Cafe Culture, Enugu',
    category: 'Art',
    image: '/images/event-poetry.webp',
    tags: ['poetry', 'open-mic'],
    tickets: [
      {
        id: 't3-1',
        name: 'General Admission',
        price: 0,
        currency: 'NGN',
        start_selling_date: '2026-01-15',
        end_selling_date: '2026-02-20',
        quantity: 0, // unlimited
      },
    ],
  },
  {
    id: '4',
    title: 'Weekend Farmers Market',
    description: 'Local vendors, fresh produce, and artisanal foods.',
    date: '2026-01-31',
    time: '08:00',
    location: 'Riverside Park, Port Harcourt',
    category: 'Food & Drink',
    image: '/images/event-market.webp',
    tags: ['market', 'family'],
    tickets: [
      {
        id: 't4-1',
        name: 'Entry Pass',
        price: 0,
        currency: 'NGN',
        start_selling_date: '2025-12-01',
        end_selling_date: '2026-01-31',
        quantity: 0,
      },
      {
        id: 't4-2',
        name: 'Vendor Stall (per day)',
        price: 5000,
        currency: 'NGN',
        start_selling_date: '2025-12-01',
        end_selling_date: '2026-01-30',
        description: 'Reserve a stall space for vendors.',
        quantity: 20,
      },
    ],
  },
  {
    id: '5',
    title: 'Startup Pitch Night',
    description: 'Early-stage founders pitch to investors and mentors.',
    date: '2026-02-28',
    time: '18:30',
    location: 'Innovation Centre, Ibadan',
    category: 'Business',
    image: '/images/event-pitch.webp',
    tags: ['startups', 'networking'],
    tickets: [
      {
        id: 't5-1',
        name: 'Pitch Attendee',
        price: 2500,
        currency: 'NGN',
        start_selling_date: '2026-01-10',
        end_selling_date: '2026-02-28',
        quantity: 150,
      },
      {
        id: 't5-2',
        name: 'Founder (Free)',
        price: 0,
        currency: 'NGN',
        start_selling_date: '2026-01-10',
        end_selling_date: '2026-02-28',
        description: 'Free tickets for presenting founders (application required).',
        quantity: 10,
      },
    ],
  },
  {
    id: '6',
    title: 'Sunrise Yoga & Wellness',
    description: 'Start your day with a guided yoga session and healthy breakfast.',
    date: '2026-02-07',
    time: '06:30',
    location: 'Seaside Lawn, Lagos',
    category: 'Health',
    image: '/images/event-yoga.webp',
    tags: ['wellness', 'outdoors'],
    tickets: [
      {
        id: 't6-1',
        name: 'Class + Breakfast',
        price: 3000,
        currency: 'NGN',
        start_selling_date: '2026-01-01',
        end_selling_date: '2026-02-06',
        quantity: 40,
      },
      {
        id: 't6-2',
        name: 'Walk-in (On the day)',
        price: 3500,
        currency: 'NGN',
        start_selling_date: '2026-01-01',
        end_selling_date: '2026-02-07',
        quantity: 0, // unlimited
      },
    ],
  },
];

export default events;
